import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'vi';

interface Translations {
  [key: string]: {
    en: string;
    vi: string;
  };
}

const translations: Translations = {
  // Dashboard
  'username': { en: 'UserName', vi: 'Tên người dùng' },
  'profile': { en: 'Profile', vi: 'Hồ sơ' },
  'vehicle_details': { en: 'Vehicle Details', vi: 'Chi tiết xe' },
  'check_subscription': { en: 'Check Subscription', vi: 'Kiểm tra gói' },
  'language': { en: 'Language', vi: 'Ngôn ngữ' },
  'logout': { en: 'LogOut', vi: 'Đăng xuất' },
  'notification': { en: 'Notification', vi: 'Thông báo' },
  'show_budget': { en: 'Show Budget', vi: 'Hiển thị ngân sách' },
  'recharge': { en: 'Recharge', vi: 'Nạp tiền' },
  'logo': { en: 'Logo', vi: 'Logo' },
  'show_model': { en: 'Show Model', vi: 'Hiển thị mẫu xe' },
  'model_name': { en: 'Model Name', vi: 'Tên mẫu xe' },
  'plate_number': { en: 'Plate Number', vi: 'Biển số xe' },
  'remain_battery': { en: 'Remain Battery', vi: 'Pin còn lại' },
  'current_battery': { en: 'Current Battery', vi: 'Pin hiện tại' },
  'battery_percentage': { en: 'Battery Percentage', vi: 'Tỷ lệ pin' },
  'enter_battery_level': { en: 'Enter your current battery level', vi: 'Nhập mức pin hiện tại' },
  'update_battery': { en: 'Update Battery', vi: 'Cập nhật pin' },
  'battery_level_updated': { en: 'Battery level updated successfully', vi: 'Cập nhật mức pin thành công' },
  'low_battery_warning': { en: 'Low battery - consider charging soon', vi: 'Pin yếu - nên sạc sớm' },
  'cancel': { en: 'Cancel', vi: 'Hủy bỏ' },
  'good_condition': { en: 'Good condition', vi: 'Tình trạng tốt' },
  'remain_km': { en: 'Remain KM', vi: 'KM còn lại' },
  'estimated_range': { en: 'Estimated range', vi: 'Phạm vi ước tính' },
  'booking_charging': { en: 'Booking Charging', vi: 'Đặt sạc' },
  'charging_session_ready': { en: 'Your charging session is ready to begin', vi: 'Phiên sạc của bạn đã sẵn sàng bắt đầu' },
  'popular': { en: 'Popular', vi: 'Phổ biến' },
  'privacy': { en: 'Privacy', vi: 'Riêng tư' },
  'guidance': { en: 'Guidance', vi: 'Hướng dẫn' },
  'history': { en: 'History', vi: 'Lịch sử' },
  'subscription': { en: 'Subscription', vi: 'Gói đăng ký' },
  'personal_analysis': { en: 'Personal Analysis', vi: 'Phân tích cá nhân' },
  'report_issue': { en: 'Report Issue', vi: 'Báo cáo sự cố' },
  'theme': { en: 'Theme', vi: 'Giao diện' },
  'light_mode': { en: 'Light Mode', vi: 'Chế độ sáng' },
  'dark_mode': { en: 'Dark Mode', vi: 'Chế độ tối' },
  
  // Profile
  'user_profile': { en: 'User Profile', vi: 'Hồ sơ người dùng' },
  'personal_information': { en: 'Personal Information', vi: 'Thông tin cá nhân' },
  'full_name': { en: 'Full Name', vi: 'Họ và tên' },
  'email': { en: 'Email', vi: 'Email' },
  'phone': { en: 'Phone', vi: 'Số điện thoại' },
  'date_of_birth': { en: 'Date of Birth', vi: 'Ngày sinh' },
  'gender': { en: 'Gender', vi: 'Giới tính' },
  'location': { en: 'Location', vi: 'Địa điểm' },
  'edit_profile': { en: 'Edit Profile', vi: 'Chỉnh sửa hồ sơ' },
  'save_changes': { en: 'Save Changes', vi: 'Lưu thay đổi' },
  
  // Vehicle
  'my_vehicle': { en: 'My Vehicle', vi: 'Xe của tôi' },
  'vehicle_information': { en: 'Vehicle Information', vi: 'Thông tin xe' },
  'brand': { en: 'Brand', vi: 'Hãng xe' },
  'model': { en: 'Model', vi: 'Mẫu xe' },
  'year': { en: 'Year', vi: 'Năm sản xuất' },
  'color': { en: 'Color', vi: 'Màu sắc' },
  'battery_capacity': { en: 'Battery Capacity', vi: 'Dung lượng pin' },
  'charging_speed': { en: 'Charging Speed', vi: 'Tốc độ sạc' },
  'range': { en: 'Range', vi: 'Phạm vi hoạt động' },
  'edit_vehicle': { en: 'Edit Vehicle', vi: 'Chỉnh sửa xe' },
  
  // Subscription
  'subscription_plans': { en: 'Subscription Plans', vi: 'Gói đăng ký' },
  'current_plan': { en: 'Current Plan', vi: 'Gói hiện tại' },
  'available_plans': { en: 'Available Plans', vi: 'Gói có sẵn' },
  'basic_plan': { en: 'Basic Plan', vi: 'Gói cơ bản' },
  'premium_plan': { en: 'Premium Plan', vi: 'Gói cao cấp' },
  'pro_plan': { en: 'Pro Plan', vi: 'Gói chuyên nghiệp' },
  'monthly': { en: 'Monthly', vi: 'Hàng tháng' },
  'yearly': { en: 'Yearly', vi: 'Hàng năm' },
  'upgrade_plan': { en: 'Upgrade Plan', vi: 'Nâng cấp gói' },
  'current': { en: 'Current', vi: 'Hiện tại' },
  
  // Login
  'chargehub': { en: 'ChargeHub', vi: 'ChargeHub' },
  'power_journey': { en: 'Power your journey with smart charging', vi: 'Tăng sức mạnh hành trình với sạc thông minh' },
  'username_email': { en: 'Username or Email', vi: 'Tên đăng nhập hoặc Email' },
  'password': { en: 'Password', vi: 'Mật khẩu' },
  'sign_in': { en: 'Sign In to ChargeHub', vi: 'Đăng nhập ChargeHub' },
  'continue_with': { en: 'or continue with', vi: 'hoặc tiếp tục với' },
  'no_account': { en: "Don't have an account?", vi: 'Chưa có tài khoản?' },
  'create_account': { en: 'Create one now', vi: 'Tạo ngay bây giờ' },
  'or': { en: 'or', vi: 'hoặc' },
  'secure_fast_reliable': { en: 'Secure • Fast • Reliable EV Charging', vi: 'An toàn • Nhanh chóng • Sạc xe điện đáng tin cậy' },
  
  // Footer
  'newsletter_signup': { en: 'Sign up to receive the latest EV news and updates', vi: 'Đăng ký nhận tin tức và cập nhật EV mới nhất' },
  'newsletter_description': { en: 'Stay informed about charging stations, new features, and special offers', vi: 'Cập nhật thông tin về trạm sạc, tính năng mới và ưu đãi đặc biệt' },
  'enter_email': { en: 'Enter your email', vi: 'Nhập email của bạn' },
  'subscribe_now': { en: 'Subscribe Now', vi: 'Đăng ký ngay' },
  'company_description': { en: 'Leading the future of electric vehicle charging with smart, reliable, and accessible charging solutions.', vi: 'Dẫn đầu tương lai sạc xe điện với các giải pháp sạc thông minh, đáng tin cậy và dễ tiếp cận.' },
  'services': { en: 'Services', vi: 'Dịch vụ' },
  'locate_fast_charger': { en: 'Locate a Fast Charger', vi: 'Tìm trạm sạc nhanh' },
  'plans_pricing': { en: 'Plans and Pricing', vi: 'Gói và giá cả' },
  'how_to_charge': { en: 'How to Charge', vi: 'Cách sạc' },
  'charging_network': { en: 'Charging Network', vi: 'Mạng lưới sạc' },
  'about_chargehub': { en: 'About ChargeHub', vi: 'Về ChargeHub' },
  'about_us': { en: 'About Us', vi: 'Về chúng tôi' },
  'careers': { en: 'Careers', vi: 'Tuyển dụng' },
  'privacy_policy': { en: 'Privacy Policy', vi: 'Chính sách bảo mật' },
  'terms_conditions': { en: 'Terms & Conditions', vi: 'Điều khoản & Điều kiện' },
  'contact_us': { en: 'Contact Us', vi: 'Liên hệ' },
  'questions_subscriptions': { en: 'Questions or Subscriptions?', vi: 'Câu hỏi hoặc đăng ký?' },
  'help_center': { en: 'Help Center', vi: 'Trung tâm trợ giúp' },
  'all_rights_reserved': { en: 'All rights reserved.', vi: 'Tất cả quyền được bảo lưu.' },
  'terms_service': { en: 'Terms of Service', vi: 'Điều khoản dịch vụ' },
  'cookies': { en: 'Cookies', vi: 'Cookie' },
  'last_charged': { en: 'Last Charged', vi: 'Lần sạc cuối' },
  'back_to_dashboard': { en: 'Back to Dashboard', vi: 'Quay về Dashboard' },
  'quick_actions': { en: 'Quick Actions', vi: 'Hành động nhanh' },
  'my_subscriptions': { en: 'My Subscriptions', vi: 'Gói đăng ký của tôi' },
  'manage_current_subscriptions': { en: 'Manage your current subscriptions and billing', vi: 'Quản lý các gói đăng ký và thanh toán hiện tại' },
  'choose_plan_description': { en: 'Choose the plan that best fits your charging needs', vi: 'Chọn gói phù hợp nhất với nhu cầu sạc của bạn' },
  'active_plan': { en: 'Active Plan', vi: 'Gói đang hoạt động' },
  'active': { en: 'Active', vi: 'Đang hoạt động' },
  'billing_history': { en: 'Billing History', vi: 'Lịch sử thanh toán' },
  'account_management': { en: 'Account Management', vi: 'Quản lý tài khoản' },
  'change_billing': { en: 'Change Billing', vi: 'Thay đổi thanh toán' },
  'usage_analytics': { en: 'Usage Analytics', vi: 'Phân tích sử dụng' },
  'cancel_subscription': { en: 'Cancel Subscription', vi: 'Hủy đăng ký' },
  
  // Role Selection
  'choose_your_role': { en: 'Choose Your Role', vi: 'Chọn vai trò của bạn' },
  'select_account_type': { en: 'Select the type of account you want to create', vi: 'Chọn loại tài khoản bạn muốn tạo' },
  'driver_account': { en: 'Driver Account', vi: 'Tài khoản tài xế' },
  'driver_description': { en: 'For EV owners looking to charge their vehicles', vi: 'Dành cho chủ xe điện muốn sạc xe của họ' },
  'staff_account': { en: 'Staff Account', vi: 'Tài khoản nhân viên' },
  'staff_description': { en: 'For charging station staff and technicians', vi: 'Dành cho nhân viên và kỹ thuật viên trạm sạc' },
  'find_charging_stations': { en: 'Find charging stations', vi: 'Tìm trạm sạc' },
  'book_charging_slots': { en: 'Book charging slots', vi: 'Đặt chỗ sạc' },
  'manage_vehicles': { en: 'Manage vehicles', vi: 'Quản lý xe' },
  'payment_history': { en: 'Payment history', vi: 'Lịch sử thanh toán' },
  'manage_stations': { en: 'Manage charging stations', vi: 'Quản lý trạm sạc' },
  'customer_support': { en: 'Customer support', vi: 'Hỗ trợ khách hàng' },
  'maintenance_reports': { en: 'Maintenance reports', vi: 'Báo cáo bảo trì' },
  'analytics_dashboard': { en: 'Analytics dashboard', vi: 'Bảng điều khiển phân tích' },
  'continue_as': { en: 'Continue as', vi: 'Tiếp tục với vai trò' },
  'driver': { en: 'Driver', vi: 'Tài xế' },
  'staff': { en: 'Staff', vi: 'Nhân viên' },
  'select_role_to_continue': { en: 'Select a role to continue', vi: 'Chọn vai trò để tiếp tục' },
  'role_change_note': { en: 'You can change your role later in account settings', vi: 'Bạn có thể thay đổi vai trò sau trong cài đặt tài khoản' },
  'back': { en: 'Back', vi: 'Quay lại' },

  // Staff Profile Setup
  'staff_profile_setup': { en: 'Staff Profile Setup', vi: 'Thiết lập hồ sơ nhân viên' },
  'complete_staff_profile': { en: 'Complete your professional profile information', vi: 'Hoàn thiện thông tin hồ sơ chuyên nghiệp của bạn' },
  'first_name': { en: 'First Name', vi: 'Tên' },
  'last_name': { en: 'Last Name', vi: 'Họ' },
  'enter_first_name': { en: 'Enter first name', vi: 'Nhập tên' },
  'enter_last_name': { en: 'Enter last name', vi: 'Nhập họ' },
  'enter_email': { en: 'Enter email', vi: 'Nhập email' },
  'enter_phone': { en: 'Enter phone number', vi: 'Nhập số điện thoại' },
  'location_information': { en: 'Location Information', vi: 'Thông tin địa điểm' },
  'country': { en: 'Country', vi: 'Quốc gia' },
  'state_province': { en: 'State/Province', vi: 'Tỉnh/Thành phố' },
  'select_country': { en: 'Select country', vi: 'Chọn quốc gia' },
  'select_state': { en: 'Select state/province', vi: 'Chọn tỉnh/thành phố' },
  'address': { en: 'Address', vi: 'Địa chỉ' },
  'enter_address': { en: 'Enter address', vi: 'Nhập địa chỉ' },
  'emergency_contact': { en: 'Emergency Contact', vi: 'Liên hệ khẩn cấp' },
  'optional': { en: 'Optional', vi: 'Tùy chọn' },
  'contact_name': { en: 'Contact Name', vi: 'Tên liên hệ' },
  'contact_phone': { en: 'Contact Phone', vi: 'Số điện thoại liên hệ' },
  'enter_contact_name': { en: 'Enter contact name', vi: 'Nhập tên liên hệ' },
  'enter_contact_phone': { en: 'Enter contact phone', vi: 'Nhập số điện thoại liên hệ' },
  'professional_bio': { en: 'Professional Bio', vi: 'Tiểu sử chuyên nghiệp' },
  'bio_description': { en: 'Brief description', vi: 'Mô tả ngắn gọn' },
  'enter_bio': { en: 'Tell us about your professional background...', vi: 'Hãy kể về kinh nghiệm chuyên nghiệp của bạn...' },
  'continue_to_education': { en: 'Continue to Education', vi: 'Tiếp tục đến học vấn' },

  // Education Setup
  'education_qualifications': { en: 'Education & Qualifications', vi: 'Học vấn & Bằng cấp' },
  'complete_education_profile': { en: 'Complete your education and qualification details', vi: 'Hoàn thiện thông tin học vấn và bằng cấp của bạn' },
  'education_history': { en: 'Education History', vi: 'Lịch sử học tập' },
  'add_education': { en: 'Add Education', vi: 'Thêm học vấn' },
  'education': { en: 'Education', vi: 'Học vấn' },
  'degree_level': { en: 'Degree Level', vi: 'Cấp độ bằng cấp' },
  'select_degree': { en: 'Select degree', vi: 'Chọn bằng cấp' },
  'institution': { en: 'Institution', vi: 'Trường học' },
  'enter_institution': { en: 'Enter institution name', vi: 'Nhập tên trường học' },
  'field_of_study': { en: 'Field of Study', vi: 'Chuyên ngành' },
  'enter_field': { en: 'Enter field of study', vi: 'Nhập chuyên ngành' },
  'gpa_score': { en: 'GPA/Score', vi: 'Điểm GPA' },
  'start_year': { en: 'Start Year', vi: 'Năm bắt đầu' },
  'end_year': { en: 'End Year', vi: 'Năm kết thúc' },
  'description': { en: 'Description', vi: 'Mô tả' },
  'education_description': { en: 'Describe your achievements, projects, or relevant coursework...', vi: 'Mô tả thành tích, dự án hoặc khóa học liên quan...' },
  'certifications': { en: 'Certifications', vi: 'Chứng chỉ' },
  'add_certification': { en: 'Add Certification', vi: 'Thêm chứng chỉ' },
  'certification': { en: 'Certification', vi: 'Chứng chỉ' },
  'certification_name': { en: 'Certification Name', vi: 'Tên chứng chỉ' },
  'enter_certification_name': { en: 'Enter certification name', vi: 'Nhập tên chứng chỉ' },
  'issuing_organization': { en: 'Issuing Organization', vi: 'Tổ chức cấp' },
  'enter_issuer': { en: 'Enter issuing organization', vi: 'Nhập tổ chức cấp chứng chỉ' },
  'issue_date': { en: 'Issue Date', vi: 'Ngày cấp' },
  'expiry_date': { en: 'Expiry Date', vi: 'Ngày hết hạn' },
  'credential_id': { en: 'Credential ID', vi: 'Mã chứng chỉ' },
  'enter_credential_id': { en: 'Enter credential ID', vi: 'Nhập mã chứng chỉ' },
  'technical_skills': { en: 'Technical Skills', vi: 'Kỹ năng kỹ thuật' },
  'enter_skill': { en: 'Enter skill', vi: 'Nhập kỹ năng' },
  'languages': { en: 'Languages', vi: 'Ngôn ngữ' },
  'enter_language': { en: 'Enter language', vi: 'Nhập ngôn ngữ' },
  'complete_staff_registration': { en: 'Complete Staff Registration', vi: 'Hoàn thành đăng ký nhân viên' },

  // Degree options
  'high_school_diploma': { en: 'High School Diploma', vi: 'Bằng tốt nghiệp THPT' },
  'associate_degree': { en: 'Associate Degree', vi: 'Bằng cao đẳng' },
  'bachelor_s_degree': { en: 'Bachelor\'s Degree', vi: 'Bằng cử nhân' },
  'master_s_degree': { en: 'Master\'s Degree', vi: 'Bằng thạc sĩ' },
  'doctoral_degree__phd_': { en: 'Doctoral Degree (PhD)', vi: 'Bằng tiến sĩ' },
  'professional_degree': { en: 'Professional Degree', vi: 'Bằng chuyên nghiệp' },
  'certification_training': { en: 'Certification/Training', vi: 'Chứng chỉ/Đào tạo' },
  'other': { en: 'Other', vi: 'Khác' },

  // Staff Home Dashboard
  'back_to_staff_portal': { en: 'Back to Staff Portal', vi: 'Quay về Staff Portal' },
  'staff_view_find_stations': { en: 'Staff View • Find Stations', vi: 'Giao diện nhân viên • Tìm trạm sạc' },
  'find_charging_stations': { en: 'Find Charging Stations', vi: 'Tìm trạm sạc' },
  'locate_monitor_stations': { en: 'Locate and monitor charging stations across the network', vi: 'Định vị và theo dõi các trạm sạc trong mạng lưới' },
  'search_stations_placeholder': { en: 'Search stations by name or location...', vi: 'Tìm kiếm trạm theo tên hoặc vị trí...' },
  'all_locations': { en: 'All Locations', vi: 'Tất cả địa điểm' },
  'district_1': { en: 'District 1', vi: 'Quận 1' },
  'district_3': { en: 'District 3', vi: 'Quận 3' },
  'district_7': { en: 'District 7', vi: 'Quận 7' },
  'all_charger_types': { en: 'All Charger Types', vi: 'Tất cả loại sạc' },
  'all_types': { en: 'All Types', vi: 'Tất cả loại' },
  'type_2': { en: 'Type 2', vi: 'Loại 2' },
  'ccs': { en: 'CCS', vi: 'CCS' },
  'chademo': { en: 'CHAdeMO', vi: 'CHAdeMO' },
  'reset_filters': { en: 'Reset Filters', vi: 'Đặt lại bộ lọc' },
  'available': { en: 'Available', vi: 'Có sẵn' },
  'busy': { en: 'Busy', vi: 'Bận' },
  'away': { en: 'away', vi: 'cách đây' },
  'available_ports': { en: 'Available Ports', vi: 'Cổng có sẵn' },
  'price_per_kwh': { en: 'Price per kWh', vi: 'Giá mỗi kWh' },
  'charger_types': { en: 'Charger Types:', vi: 'Loại sạc:' },
  'amenities': { en: 'Amenities:', vi: 'Tiện ích:' },
  'view_details': { en: 'View Details', vi: 'Xem chi tiết' },
  'no_stations_found': { en: 'No stations found', vi: 'Không tìm thấy trạm nào' },
  'adjust_search_criteria': { en: 'Try adjusting your search criteria or filters', vi: 'Thử điều chỉnh tiêu chí tìm kiếm hoặc bộ lọc' },
  'staff_information': { en: 'Staff Information', vi: 'Thông tin nhân viên' },
  'staff_view_note': { en: 'This is the staff view of the charging station finder. Customer booking and payment features are not available in this view.', vi: 'Đây là giao diện nhân viên của công cụ tìm trạm sạc. Các tính năng đặt chỗ và thanh toán của khách hàng không có sẵn trong giao diện này.' },
  'parking': { en: 'Parking', vi: 'Bãi đỗ xe' },
  'wifi': { en: 'WiFi', vi: 'WiFi' },
  'cafe': { en: 'Cafe', vi: 'Quán cà phê' },
  'security': { en: 'Security', vi: 'Bảo vệ' },

  // Staff Dashboard New Features
  'billing_invoice': { en: 'Billing & Invoice', vi: 'Hóa đơn & Thanh toán' },
  'report_issues': { en: 'Report Issues', vi: 'Báo cáo sự cố' },
  'support_tickets': { en: 'Support Tickets', vi: 'Ticket hỗ trợ' },
  'pending_invoices': { en: 'Pending Invoices', vi: 'Hóa đơn chờ xử lý' },
  'open_reports': { en: 'Open Reports', vi: 'Báo cáo đang mở' },
  'create_invoice': { en: 'Create Invoice', vi: 'Tạo hóa đơn' },
  'generate_customer_invoices': { en: 'Generate customer invoices', vi: 'Tạo hóa đơn khách hàng' },
  'submit_equipment_reports': { en: 'Submit equipment or other reports', vi: 'Gửi báo cáo thiết bị hoặc khác' },
  'view_system_alerts': { en: 'View system alerts', vi: 'Xem cảnh báo hệ thống' },
  'help_customers_issues': { en: 'Help customers with issues', vi: 'Hỗ trợ khách hàng giải quyết vấn đề' },

  // Invoice Management
  'invoice_management': { en: 'Invoice Management', vi: 'Quản lý hóa đơn' },
  'create_manage_invoices': { en: 'Create and manage customer invoices', vi: 'Tạo và quản lý hóa đơn khách hàng' },
  'create_new_invoice': { en: 'Create New Invoice', vi: 'Tạo hóa đơn mới' },
  'view_invoices': { en: 'View Invoices', vi: 'Xem hóa đơn' },
  'customer_information': { en: 'Customer Information', vi: 'Thông tin khách hàng' },
  'search_customers': { en: 'Search customers...', vi: 'Tìm kiếm khách hàng...' },
  'selected_customer': { en: 'Selected Customer:', vi: 'Khách hàng đã chọn:' },
  'invoice_items': { en: 'Invoice Items', vi: 'Danh mục hóa đơn' },
  'add_item': { en: 'Add Item', vi: 'Thêm mục' },
  'description': { en: 'Description', vi: 'Mô tả' },
  'quantity': { en: 'Qty', vi: 'SL' },
  'unit_price': { en: 'Unit Price', vi: 'Đơn giá' },
  'total_amount': { en: 'Total Amount', vi: 'Tổng tiền' },
  'save_as_draft': { en: 'Save as Draft', vi: 'Lưu bản nháp' },
  'create_send_invoice': { en: 'Create & Send Invoice', vi: 'Tạo & Gửi hóa đơn' },
  'invoice_history': { en: 'Invoice History', vi: 'Lịch sử hóa đơn' },
  'manage_existing_invoices': { en: 'Manage existing invoices and payments', vi: 'Quản lý hóa đơn và thanh toán hiện có' },
  'download_pdf': { en: 'Download PDF', vi: 'Tải PDF' },
  'process_payment': { en: 'Process Payment', vi: 'Xử lý thanh toán' },

  // Report Management
  'report_management': { en: 'Report Management', vi: 'Quản lý báo cáo' },
  'submit_track_reports': { en: 'Submit and track maintenance reports', vi: 'Gửi và theo dõi báo cáo bảo trì' },
  'equipment_reports': { en: 'Equipment Reports', vi: 'Báo cáo thiết bị' },
  'other_issues': { en: 'Other Issues', vi: 'Vấn đề khác' },
  'report_history': { en: 'Report History', vi: 'Lịch sử báo cáo' },
  'customer_equipment_reports': { en: 'Customer Equipment Reports', vi: 'Báo cáo thiết bị từ khách hàng' },
  'review_customer_reports': { en: 'Review customer-reported equipment issues', vi: 'Xem xét các vấn đề thiết bị do khách hàng báo cáo' },
  'customer_report': { en: 'Customer Report', vi: 'Báo cáo khách hàng' },
  'station': { en: 'Station', vi: 'Trạm' },
  'equipment': { en: 'Equipment', vi: 'Thiết bị' },
  'issue': { en: 'Issue', vi: 'Vấn đề' },
  'date': { en: 'Date', vi: 'Ngày' },
  'create_report': { en: 'Create Report', vi: 'Tạo báo cáo' },
  'new_equipment_report': { en: 'New Equipment Report', vi: 'Báo cáo thiết bị mới' },
  'submit_equipment_damage': { en: 'Submit equipment damage or malfunction report', vi: 'Gửi báo cáo hư hỏng hoặc trục trặc thiết bị' },
  'report_source': { en: 'Report Source', vi: 'Nguồn báo cáo' },
  'staff_inspection': { en: 'Staff Inspection', vi: 'Kiểm tra nhân viên' },
  'customer_report_followup': { en: 'Customer Report Follow-up', vi: 'Theo dõi báo cáo khách hàng' },
  'select_station': { en: 'Select station', vi: 'Chọn trạm' },
  'select_equipment': { en: 'Select equipment', vi: 'Chọn thiết bị' },
  'equipment_type': { en: 'Equipment Type', vi: 'Loại thiết bị' },
  'report_title': { en: 'Report Title', vi: 'Tiêu đề báo cáo' },
  'brief_issue_description': { en: 'Brief description of the issue', vi: 'Mô tả ngắn gọn về vấn đề' },
  'priority_level': { en: 'Priority Level', vi: 'Mức độ ưu tiên' },
  'detailed_description': { en: 'Detailed Description', vi: 'Mô tả chi tiết' },
  'equipment_issue_details': { en: 'Provide detailed information about the equipment issue, symptoms, and any troubleshooting steps taken...', vi: 'Cung cấp thông tin chi tiết về vấn đề thiết bị, triệu chứng và các bước khắc phục đã thực hiện...' },
  'photos_optional': { en: 'Photos (Optional)', vi: 'Ảnh (Tùy chọn)' },
  'upload_equipment_photos': { en: 'Upload photos of the equipment issue', vi: 'Tải lên ảnh của vấn đề thiết bị' },
  'choose_photos': { en: 'Choose Photos', vi: 'Chọn ảnh' },
  'reset_form': { en: 'Reset Form', vi: 'Đặt lại form' },
  'submit_report': { en: 'Submit Report', vi: 'Gửi báo cáo' },
  'report_other_issues': { en: 'Report Other Issues', vi: 'Báo cáo vấn đề khác' },
  'non_equipment_problems': { en: 'Submit reports for non-equipment related problems', vi: 'Gửi báo cáo cho các vấn đề không liên quan đến thiết bị' },
  'station_optional': { en: 'Station (Optional)', vi: 'Trạm (Tùy chọn)' },
  'no_specific_station': { en: 'No specific station', vi: 'Không có trạm cụ thể' },
  'issue_title': { en: 'Issue Title', vi: 'Tiêu đề vấn đề' },
  'issue_description_placeholder': { en: 'Describe the issue in detail (e.g., lighting problems, cleanliness issues, safety concerns, parking problems, etc.)', vi: 'Mô tả vấn đề chi tiết (ví dụ: vấn đề chiếu sáng, vệ sinh, an toàn, bãi đỗ xe, v.v.)' },
  'upload_support_photos': { en: 'Upload photos to support your report', vi: 'Tải lên ảnh để hỗ trợ báo cáo của bạn' },
  'view_track_reports': { en: 'View and track submitted reports', vi: 'Xem và theo dõi các báo cáo đã gửi' },
  'type': { en: 'Type', vi: 'Loại' },
  'related_customer_report': { en: 'Related to customer report:', vi: 'Liên quan đến báo cáo khách hàng:' },
  'view_details': { en: 'View Details', vi: 'Xem chi tiết' },

  // Status and Priority
  'low': { en: 'Low', vi: 'Thấp' },
  'medium': { en: 'Medium', vi: 'Trung bình' },
  'high': { en: 'High', vi: 'Cao' },
  'critical': { en: 'Critical', vi: 'Nghiêm trọng' },
  'draft': { en: 'Draft', vi: 'Bản nháp' },
  'submitted': { en: 'Submitted', vi: 'Đã gửi' },
  'in_progress': { en: 'In Progress', vi: 'Đang xử lý' },
  'resolved': { en: 'Resolved', vi: 'Đã giải quyết' },
  'paid': { en: 'Paid', vi: 'Đã thanh toán' },
  'pending': { en: 'Pending', vi: 'Chờ xử lý' },
  'overdue': { en: 'Overdue', vi: 'Quá hạn' },

  // Notifications
  'unread': { en: 'Unread', vi: 'Chưa đọc' },
  'today': { en: 'Today', vi: 'Hôm nay' },
  'recent_notifications': { en: 'Recent Notifications', vi: 'Thông báo gần đây' },

  // Additional Staff Dashboard translations
  'staff_dashboard': { en: 'Staff Dashboard', vi: 'Bảng điều khiển nhân viên' },
  'welcome_staff_portal': { en: 'Welcome to ChargeHub Staff Portal', vi: 'Chào mừng đến với Cổng thông tin nhân viên ChargeHub' },
  'dashboard': { en: 'Dashboard', vi: 'Bảng điều khiển' },

  // Payment and QR Code translations
  'payment_successful': { en: 'Payment Successful!', vi: 'Thanh toán thành công!' },
  'invoice_paid': { en: 'has been paid', vi: 'đã được thanh toán' },
  'payment_method': { en: 'Payment Method:', vi: 'Phương thức thanh toán:' },
  'amount_paid': { en: 'Amount Paid:', vi: 'Số tiền đã thanh toán:' },
  'savings': { en: 'Savings:', vi: 'Tiết kiệm được:' },
  'invoice_sent_email': { en: 'Invoice sent via email', vi: 'Hóa đơn đã được gửi qua email' },
  'sending_invoice': { en: 'Sending invoice...', vi: 'Đang gửi hóa đơn...' },
  'back_to_dashboard': { en: 'Back to Dashboard', vi: 'Quay về Dashboard' },
  'invoice_payment': { en: 'Invoice Payment', vi: 'Thanh toán hóa đơn' },
  'customer_information': { en: 'Customer Information', vi: 'Thông tin khách hàng' },
  'payment_details': { en: 'Payment Details', vi: 'Chi tiết thanh toán' },
  'original_amount': { en: 'Original Amount:', vi: 'Tổng tiền gốc:' },
  'total_amount': { en: 'Total Amount:', vi: 'Tổng thanh toán:' },
  'scan_qr_code': { en: 'Scan QR Code', vi: 'Quét mã QR' },
  'expires_in': { en: 'Expires in:', vi: 'Hết hạn sau:' },
  'cash_payment': { en: 'Cash Payment', vi: 'Thanh toán tiền mặt' },
  'customer_pays_cash': { en: 'Customer pays with cash', vi: 'Khách hàng thanh toán bằng tiền mặt' },
  'confirm_qr_payment': { en: 'Confirm QR Payment', vi: 'Xác nhận thanh toán QR' },
  'confirm_cash_payment': { en: 'Confirm Cash Payment', vi: 'Xác nhận thanh toán mặt' },
  'processing': { en: 'Processing...', vi: 'Đang xử lý...' },
  'invoice_items': { en: 'Invoice Items', vi: 'Chi tiết hóa đơn' },
  
  // Additional Invoice Management
  'back_to_dashboard': { en: 'Back to Dashboard', vi: 'Quay về Dashboard' },
  'create_detailed_invoice': { en: 'Create Detailed Invoice', vi: 'Tạo hóa đơn chi tiết' },
  'comprehensive_invoice_builder': { en: 'Use our comprehensive invoice builder to create detailed invoices with multiple items, taxes, and payment options.', vi: 'Sử dụng công cụ tạo hóa đơn toàn diện để tạo hóa đơn chi tiết với nhiều mục, thuế và tùy chọn thanh toán.' },
  'start_creating_invoice': { en: 'Start Creating Invoice', vi: 'Bắt đầu tạo hóa đơn' },
  
  // Settings
  'settings': { en: 'Settings', vi: 'Cài đặt' },
  'appearance': { en: 'Appearance', vi: 'Giao diện' },
  'dark': { en: 'Dark', vi: 'Tối' },
  'light': { en: 'Light', vi: 'Sáng' },
  'display_language': { en: 'Display Language', vi: 'Ngôn ngữ hiển thị' },
  'system_logs': { en: 'System Logs', vi: 'Nhật ký hệ thống' },
  'view_system_logs_monitoring': { en: 'View system logs and activity monitoring.', vi: 'Xem nhật ký hệ thống và giám sát hoạt động.' },
  'view_logs': { en: 'View Logs', vi: 'Xem nhật ký' },
  'backup': { en: 'Backup', vi: 'Sao lưu' },
  'system_backup_recovery': { en: 'System backup and recovery options.', vi: 'Tùy chọn sao lưu và khôi phục hệ thống.' },
  'manage_backup': { en: 'Manage Backup', vi: 'Quản lý sao lưu' },
  'security': { en: 'Security', vi: 'Bảo mật' },
  'security_access_control': { en: 'Security settings and access control.', vi: 'Cài đặt bảo mật và kiểm soát truy cập.' },
  'security_settings': { en: 'Security Settings', vi: 'Cài đặt bảo mật' },
  
  // Additional button text
  'staff_login': { en: 'Staff Login', vi: 'Đăng nhập nhân viên' },
  'sign_in_to_admin': { en: 'Sign In To Staff', vi: 'Đăng nhập nhân viên' },
  'log_in_to_admin': { en: 'Log In To Admin', vi: 'Đăng nhập Admin' },
  'switch_to_dark': { en: 'Switch to Dark', vi: 'Chuyển sang tối' },
  'switch_to_light': { en: 'Switch to Light', vi: 'Chuyển sang sáng' },
  'all_settings': { en: 'All Settings', vi: 'Tất cả cài đặt' },
  'tieng_viet': { en: 'Tiếng Việt', vi: 'Tiếng Việt' },
  'english': { en: 'English', vi: 'English' },

  // Admin Portal Translations
  'admin_portal': { en: 'Admin Portal', vi: 'Cổng Quản Trị' },
  'restricted_access': { en: 'Restricted', vi: 'Hạn chế' },
  'admin_portal_description': { en: 'Secure administrative access to system management', vi: 'Truy cập quản trị bảo mật cho quản lý hệ thống' },
  'high_security_area': { en: 'High Security Area', vi: 'Khu Vực Bảo Mật Cao' },
  'admin_access_warning': { en: 'Unauthorized access attempts are logged and monitored', vi: 'Các lần truy cập trái phép được ghi lại và giám sát' },
  'admin_id': { en: 'Administrator ID', vi: 'ID Quản Trị Viên' },
  'enter_admin_id': { en: 'Enter your administrator ID', vi: 'Nhập ID quản trị viên' },
  'admin_password': { en: 'Administrator Password', vi: 'Mật Khẩu Quản Trị' },
  'enter_admin_password': { en: 'Enter your secure password', vi: 'Nhập mật khẩu bảo mật' },
  'authenticating': { en: 'Authenticating...', vi: 'Đang xác thực...' },
  'access_admin_portal': { en: 'Access Admin Portal', vi: 'Truy Cập Cổng Quản Trị' },
  'protected_by': { en: 'Protected by advanced security', vi: 'Được bảo vệ bởi bảo mật nâng cao' },
  'multi_factor_auth': { en: '2FA Required', vi: 'Yêu cầu 2FA' },
  'encrypted_connection': { en: 'SSL Encrypted', vi: 'Mã hóa SSL' },
  'access_logging': { en: 'Access Logging', vi: 'Ghi nhật ký' },
  'session_timeout': { en: 'Auto Timeout', vi: 'Tự động hết hạn' },
  'admin_footer_notice': { en: 'All administrative actions are logged for security audit', vi: 'Tất cả hành động quản trị được ghi lại để kiểm toán bảo mật' },
  'system_administrator_only': { en: 'System Administrator Only', vi: 'Chỉ Quản Trị Viên Hệ Thống' },

  // Penalty Rules Management
  'add_new_penalty_rule': { en: 'Add New Penalty Rule', vi: 'Thêm quy tắc phạt mới' },
  'new_penalty_rule': { en: 'New Penalty Rule', vi: 'Quy tắc phạt mới' },
  'create_custom_penalty': { en: 'Create custom penalty rule', vi: 'Tạo quy tắc phạt tùy chỉnh' },
  'rule_name': { en: 'Rule Name', vi: 'Tên quy tắc' },
  'enter_rule_name': { en: 'Enter rule name', vi: 'Nhập tên quy tắc' },
  'rule_category': { en: 'Rule Category', vi: 'Danh mục quy tắc' },
  'select_category': { en: 'Select category', vi: 'Chọn danh mục' },
  'parking_violations': { en: 'Parking Violations', vi: 'Vi phạm đỗ xe' },
  'charging_violations': { en: 'Charging Violations', vi: 'Vi phạm sạc' },
  'time_violations': { en: 'Time Violations', vi: 'Vi phạm thời gian' },
  'equipment_misuse': { en: 'Equipment Misuse', vi: 'Sử dụng thiết bị sai cách' },
  'violation_description': { en: 'Violation Description', vi: 'Mô tả vi phạm' },
  'describe_violation': { en: 'Describe what constitutes this violation...', vi: 'Mô tả hành vi nào cấu thành vi phạm này...' },
  'penalty_amount': { en: 'Penalty Amount (VND)', vi: 'Số tiền phạt (VND)' },
  'enter_penalty_amount': { en: 'Enter penalty amount', vi: 'Nhập số tiền phạt' },
  'penalty_unit': { en: 'Penalty Unit', vi: 'Đơn vị phạt' },
  'fixed_amount': { en: 'Fixed Amount', vi: 'Số tiền cố định' },
  'per_hour': { en: 'Per Hour', vi: 'Mỗi giờ' },
  'per_15_minutes': { en: 'Per 15 Minutes', vi: 'Mỗi 15 phút' },
  'per_violation': { en: 'Per Violation', vi: 'Mỗi vi phạm' },
  'rule_status': { en: 'Rule Status', vi: 'Trạng thái quy tắc' },
  'effective_date': { en: 'Effective Date', vi: 'Ngày có hiệu lực' },
  'select_effective_date': { en: 'Select effective date', vi: 'Chọn ngày có hiệu lực' },
  'additional_notes': { en: 'Additional Notes', vi: 'Ghi chú thêm' },
  'optional_notes': { en: 'Optional notes or conditions...', vi: 'Ghi chú hoặc điều kiện tùy chọn...' },
  'create_rule': { en: 'Create Rule', vi: 'Tạo quy tắc' },
  'cancel': { en: 'Cancel', vi: 'Hủy' },
  'penalty_rules_list': { en: 'Penalty Rules List', vi: 'Danh sách quy tắc phạt' },
  'manage_existing_rules': { en: 'Manage existing penalty rules', vi: 'Quản lý các quy tắc phạt hiện có' },
  'rule_created_successfully': { en: 'Penalty rule created successfully', vi: 'Tạo quy tắc phạt thành công' },
  'edit_rule': { en: 'Edit Rule', vi: 'Chỉnh sửa quy tắc' },
  'delete_rule': { en: 'Delete Rule', vi: 'Xóa quy tắc' },
  'status': { en: 'Status', vi: 'Trạng thái' },
  'effective_from': { en: 'Effective From', vi: 'Có hiệu lực từ' },
  'actions': { en: 'Actions', vi: 'Hành động' },
  'hour': { en: 'hour', vi: 'giờ' },
  'min': { en: 'minutes', vi: 'phút' },

  // Personal Analysis Translations
  'personal_analysis_insights': { en: 'AI-powered insights for your charging habits', vi: 'Phân tích thông minh về thói quen sạc' },
  'overview': { en: 'Overview', vi: 'Tổng Quan' },
  'recommendations': { en: 'Recommendations', vi: 'Gợi Ý' },
  'trends': { en: 'Trends', vi: 'Xu Hướng' },
  
  // Overview Tab
  'efficiency_score': { en: 'Efficiency Score', vi: 'Điểm Hiệu Quả' },
  'above_average': { en: 'Above average', vi: 'Trên trung bình' },
  'monthly_savings': { en: 'Monthly Savings', vi: 'Tiết Kiệm Hàng Tháng' },
  'potential_with_premium': { en: 'Potential with Premium', vi: 'Tiềm năng với Premium' },
  'usage_trend': { en: 'Usage Trend', vi: 'Xu Hướng Sử Dụng' },
  'vs_last_month': { en: 'vs last month', vi: 'so với tháng trước' },
  'your_charging_patterns': { en: 'Your Charging Patterns', vi: 'Thói Quen Sạc Của Bạn' },
  'preferred_time_slots': { en: 'Preferred Time Slots', vi: 'Khung Giờ Ưa Thích' },
  'station_preferences': { en: 'Station Preferences', vi: 'Trạm Ưa Thích' },
  'total_sessions': { en: 'Total Sessions', vi: 'Tổng Phiên' },
  'kwh_charged': { en: 'kWh Charged', vi: 'kWh Đã Sạc' },
  'avg_duration': { en: 'Avg Duration', vi: 'Thời Gian TB' },
  'avg_rating': { en: 'Avg Rating', vi: 'Đánh Giá TB' },
  
  // Recommendations Tab
  'station_recommendations': { en: 'Station Recommendations', vi: 'Gợi Ý Trạm Sạc' },
  'based_on_history': { en: 'Based on your charging history and preferences', vi: 'Dựa trên lịch sử và sở thích sạc của bạn' },
  'favorite': { en: 'Favorite', vi: 'Yêu Thích' },
  'discovery': { en: 'Discovery', vi: 'Khám Phá' },
  'return_to_favorite': { en: 'Return to Your Favorite', vi: 'Quay Lại Trạm Yêu Thích' },
  'try_something_new': { en: 'Try Something New', vi: 'Thử Cái Gì Mới' },
  'book_again': { en: 'Book Again', vi: 'Đặt Lại' },
  'explore_station': { en: 'Explore Station', vi: 'Khám Phá Trạm' },
  'optimal_timing': { en: 'Optimal Timing', vi: 'Thời Gian Tối Ưu' },
  'smart_scheduling': { en: 'Smart scheduling based on your patterns', vi: 'Lịch trình thông minh dựa trên thói quen của bạn' },
  'optimal_charging_window': { en: 'Optimal Charging Window', vi: 'Khung Giờ Sc Tối Ưu' },
  'avoid_peak_hours': { en: 'Avoid Peak Hours', vi: 'Tránh Giờ Cao Điểm' },
  'subscription_recommendations': { en: 'Subscription Recommendations', vi: 'Gợi Ý Gói Đăng Ký' },
  'save_money_right_plan': { en: 'Save money with the right plan for your usage', vi: 'Tiết kiệm tiền với gói phù hợp cho việc sử dụng của bạn' },
  'chargehub_premium': { en: 'ChargeHub Premium', vi: 'ChargeHub Premium' },
  'chargehub_basic': { en: 'ChargeHub Basic', vi: 'ChargeHub Basic' },
  'highly_recommended': { en: 'HIGHLY RECOMMENDED', vi: 'RẤT ĐƯỢC KHUYẾN NGHỊ' },
  'good_value': { en: 'GOOD VALUE', vi: 'GIÁ TRỊ TỐT' },
  'choose_plan': { en: 'Choose Plan', vi: 'Chọn Gói' },
  'features': { en: 'Features', vi: 'Tính Năng' },
  'savings_projection': { en: 'Savings Projection', vi: 'Dự Báo Tiết Kiệm' },
  'current_monthly_savings': { en: 'Current Monthly Savings', vi: 'Tiết Kiệm Hàng Tháng Hiện Tại' },
  'projected_monthly_savings': { en: 'Projected Monthly Savings', vi: 'Tiết Kiệm Hàng Tháng Dự Báo' },
  
  // Trends Tab
  'usage_trends': { en: 'Usage Trends', vi: 'Xu Hướng Sử Dụng' },
  'charging_activity_6_months': { en: 'Your charging activity over the last 6 months', vi: 'Hoạt động sạc của bạn trong 6 tháng qua' },
  'growing_usage': { en: 'Growing Usage', vi: 'Sử Dụng Tăng Trưởng' },
  'increase_vs_nov': { en: '150% increase vs Nov', vi: 'Tăng 150% so với tháng 11' },
  'monthly_spend': { en: 'Monthly Spend', vi: 'Chi Tiêu Hàng Tháng' },
  'in_dec': { en: 'in Dec', vi: 'trong tháng 12' },
  'energy_usage': { en: 'Energy Usage', vi: 'Sử Dụng Năng Lượng' },
  'charging_habits_analysis': { en: 'Charging Habits Analysis', vi: 'Phân Tích Thói Quen Sạc' },
  'charging_efficiency': { en: 'Charging Efficiency', vi: 'Hiệu Quả Sạc' },
  'energy_per_session': { en: 'Energy per session', vi: 'Năng lượng mỗi phiên' },
  'preferred_charger': { en: 'Preferred charger', vi: 'Loại sạc ưa thích' },
  'cost_efficiency_score': { en: 'Cost Efficiency Score', vi: 'Điểm Hiệu Quả Chi Phí' },
  'your_score': { en: 'Your Score', vi: 'Điểm Của Bạn' },
  'more_efficient_than': { en: 'You\'re more efficient than 78% of ChargeHub users', vi: 'Bạn hiệu quả hơn 78% người dùng ChargeHub' },
  'great_job_efficient': { en: 'Great job! Your charging habits are highly efficient.', vi: 'Làm tốt lắm! Thói quen sạc của bạn rất hiệu quả.' },
  
  // Time slots
  'morning_6am_12pm': { en: 'Morning (6AM-12PM)', vi: 'Buổi sáng (6AM-12PM)' },
  'afternoon_12pm_6pm': { en: 'Afternoon (12PM-6PM)', vi: 'Buổi chiều (12PM-6PM)' },
  'evening_6pm_11pm': { en: 'Evening (6PM-11PM)', vi: 'Buổi tối (6PM-11PM)' },
  
  // Recommendation details
  'rated_5_stars_consistently': { en: 'You\'ve rated this station 5 stars consistently. Book your next session here for reliable service.', vi: 'Bạn đã đánh giá trạm này 5 sao liên tục. Đặt phiên tiếp theo ở đây để có dịch vụ đáng tin cậy.' },
  'save_15_percent_discount': { en: 'Save 15% with frequent user discount', vi: 'Tiết kiệm 15% với ưu đãi người dùng thường xuyên' },
  'similar_amenities_better_price': { en: 'Based on your location patterns, this station offers similar amenities at a better price point.', vi: 'Dựa trên thói quen địa điểm của bạn, trạm này có tiện ích tương tự với giá tốt hơn.' },
  'potential_12_percent_savings': { en: 'Potential 12% cost savings', vi: 'Tiềm năng tiết kiệm 12% chi phí' },
  'afternoon_sessions_efficient': { en: 'Based on your history, afternoon sessions are 35% more efficient and cost-effective.', vi: 'Dựa trên lịch sử của bạn, các phiên chiều hiệu quả và tiết kiệm hơn 35%.' },
  'lower_rates_faster_charging': { en: 'Lower rates + faster charging', vi: 'Giá thấp hơn + sạc nhanh hơn' },
  'evening_sessions_higher_wait': { en: 'Evening sessions in your history show higher wait times and premium pricing.', vi: 'Các phiên tối trong lịch sử của bạn cho thấy thời gian chờ cao hơn và giá cao cấp.' },
  'save_20_percent_shifting_time': { en: 'Save up to 20% by shifting time', vi: 'Tiết kiệm tới 20% bằng cách dời thời gian' },
  
  // Subscription features
  '15_percent_discount_all_stations': { en: '15% discount at all stations', vi: 'Giảm 15% tại tất cả trạm' },
  'priority_booking': { en: 'Priority booking', vi: 'Đặt chỗ ưu tiên' },
  'free_session_cancellation': { en: 'Free session cancellation', vi: 'Hủy phiên miễn phí' },
  '24_7_support': { en: '24/7 support', vi: 'Hỗ trợ 24/7' },
  '10_percent_discount_partner_stations': { en: '10% discount at partner stations', vi: 'Giảm 10% tại trạm đối tác' },
  'basic_booking': { en: 'Basic booking', vi: 'Đặt chỗ cơ bản' },
  'email_support': { en: 'Email support', vi: 'Hỗ trợ email' },
  'save_29_percent_annually': { en: 'Based on your 4+ sessions per month, you\'ll save 29% annually', vi: 'Dựa trên 4+ phiên/tháng của bạn, bạn sẽ tiết kiệm 29% hàng năm' },
  'suitable_current_usage': { en: 'Suitable for your current usage pattern with decent savings', vi: 'Phù hợp với thói quen sử dụng hiện tại với tiết kiệm hợp lý' },

  // BookingMap Translations  
  'your_location': { en: 'Your Location', vi: 'Vị Trí Của Bạn' },
  'ultra_fast': { en: 'Ultra Fast', vi: 'Siêu Nhanh' },
  'fast': { en: 'Fast', vi: 'Nhanh' },
  'standard': { en: 'Standard', vi: 'Tiêu Chuẩn' },
  'nearby_stations': { en: 'Nearby Stations', vi: 'Trạm Gần Đây' },
  'search_stations': { en: 'Search stations by name or location...', vi: 'Tìm kiếm trạm theo tên hoặc vị trí...' },
  'filters': { en: 'Filters', vi: 'Bộ Lọc' },
  'advanced_filters': { en: 'Advanced Filters', vi: 'Bộ Lọc Nâng Cao' },
  'price_range': { en: 'Price Range', vi: 'Khoảng Giá' },
  'power_levels': { en: 'Power Levels', vi: 'Mức Công Suất' },
  'operators': { en: 'Operators', vi: 'Nhà Vận Hành' },
  'show_available_only': { en: 'Show available only', vi: 'Chỉ hiển thị có sẵn' },
  'fast_charging_only': { en: 'Fast charging only', vi: 'Chỉ sạc nhanh' },
  'open_24h': { en: 'Open 24h', vi: 'Mở cửa 24h' },
  'clear_filters': { en: 'Clear Filters', vi: 'Xóa Bộ Lọc' },
  'apply_filters': { en: 'Apply Filters', vi: 'Áp Dụng Bộ Lọc' },
  'stations_found': { en: 'stations found', vi: 'trạm tìm thấy' },
  'no_stations_found_message': { en: 'No stations found matching your criteria', vi: 'Không tìm thấy trạm nào phù hợp với tiêu chí của bạn' },
  'select_station': { en: 'Select a station to view details', vi: 'Chọn trạm để xem chi tiết' },
  'station_details': { en: 'Station Details', vi: 'Chi Tiết Trạm' },
  'available_ports_label': { en: 'Available Ports', vi: 'Cổng Có Sẵn' },
  'charger_types_label': { en: 'Charger Types', vi: 'Loại Sạc' },
  'operating_hours': { en: 'Operating Hours', vi: 'Giờ Hoạt Động' },
  'reviews': { en: 'reviews', vi: 'đánh giá' },
  'book_this_station': { en: 'Book This Station', vi: 'Đặt Trạm Này' },
  'get_directions': { en: 'Get Directions', vi: 'Lấy Chỉ Đường' },
  'call_station': { en: 'Call Station', vi: 'Gọi Trạm' },
  'share_station': { en: 'Share Station', vi: 'Chia Sẻ Trạm' },
  'estimated_wait_time': { en: 'Estimated Wait Time', vi: 'Thời Gian Chờ Ước Tính' },
  'last_updated': { en: 'Last Updated', vi: 'Cập Nhật Lần Cuối' },
  'weather_conditions': { en: 'Weather Conditions', vi: 'Điều Kiện Thời Tiết' },
  'temperature': { en: 'Temperature', vi: 'Nhiệt Độ' },
  'humidity': { en: 'Humidity', vi: 'Độ Ẩm' },
  'minutes_ago': { en: 'mins ago', vi: 'phút trước' },
  'hours_ago': { en: 'hours ago', vi: 'giờ trước' },
  'maintenance': { en: 'Maintenance', vi: 'Bảo Trì' },
  'coming_soon': { en: 'Coming Soon', vi: 'Sắp Ra Mắt' },
  'find_charging_stations_title': { en: 'Find Charging Stations', vi: 'Tìm Trạm Sạc' },
  'search_placeholder': { en: 'Search for stations...', vi: 'Tìm kiếm trạm...' },
  'loading': { en: 'Loading...', vi: 'Đang tải...' },
  'book_now': { en: 'Book Now', vi: 'Đặt Ngay' },
  'view_details': { en: 'View Details', vi: 'Xem Chi Tiết' },
  'distance': { en: 'Distance', vi: 'Khoảng Cách' },
  'rating': { en: 'Rating', vi: 'Đánh Giá' },
  'price_per_kwh': { en: 'Price per kWh', vi: 'Giá mỗi kWh' },
  'amenities': { en: 'Amenities', vi: 'Tiện Ích' },
  'photos': { en: 'Photos', vi: 'Hình Ảnh' },
  'more_info': { en: 'More Info', vi: 'Thêm Thông Tin' },
  'show_route': { en: 'Show Route', vi: 'Hiển Thị Đường Đi' },
  'hide_route': { en: 'Hide Route', vi: 'Ẩn Đường Đi' },
  'refresh_map': { en: 'Refresh Map', vi: 'Làm Mới Bản Đồ' },
  'zoom_in': { en: 'Zoom In', vi: 'Phóng To' },
  'zoom_out': { en: 'Zoom Out', vi: 'Thu Nhỏ' },
  'toggle_satellite': { en: 'Toggle Satellite View', vi: 'Chuyển Đổi Xem Vệ Tinh' },
  'center_location': { en: 'Center on My Location', vi: 'Căn Giữa Vị Trí Của Tôi' },

  // History View Additional Translations
  'duration': { en: 'Duration', vi: 'Thời Gian' },
  'energy': { en: 'Energy', vi: 'Năng Lượng' },
  'charger': { en: 'Charger', vi: 'Sạc' },
  'payment': { en: 'Payment', vi: 'Thanh Toán' },
  'credit_card': { en: 'Credit Card', vi: 'Thẻ Tín Dụng' },
  'digital_wallet': { en: 'Digital Wallet', vi: 'Ví Điện Tử' },

  // Report Issue Additional Translations
  'station_malfunction': { en: 'Station malfunction', vi: 'Trạm bị hỏng' },
  'fast_charging_clean_station': { en: 'Fast charging, clean station', vi: 'Sạc nhanh, trạm sạch sẽ' },
  'good_location_slightly_slow': { en: 'Good location, slightly slow', vi: 'Vị trí tốt, hơi chậm' },
  'excellent_service_shopping_nearby': { en: 'Excellent service, shopping nearby', vi: 'Dịch vụ xuất sắc, có chỗ mua sắm gần' },
  'convenient_location': { en: 'Convenient location', vi: 'Vị trí thuận tiện' },
  'currently_charging': { en: 'Currently charging', vi: 'Đang sạc' },

  // System Config Translations
  'system_configuration': { en: 'System Configuration', vi: 'Cấu Hình Hệ Thống' },
  'system_config': { en: 'System Config', vi: 'Cấu Hình Hệ Thống' },
  'manage_pricing_settings': { en: 'Manage pricing and system settings', vi: 'Quản lý giá cả và cài đặt hệ thống' },
  'station_pricing': { en: 'Station Pricing', vi: 'Giá Trạm Sạc' },
  'peak_hours': { en: 'Peak Hours', vi: 'Giờ Cao Điểm' },
  'penalties': { en: 'Penalties', vi: 'Phí Phạt' },
  'subscriptions': { en: 'Subscriptions', vi: 'Gói Đăng Ký' },
  'station_pricing_management': { en: 'Station Pricing Management', vi: 'Quản Lý Giá Trạm Sạc' },
  'set_pricing_stations': { en: 'Set pricing for individual charging stations', vi: 'Đặt giá cho từng trạm sạc riêng biệt' },
  'current_pricing': { en: 'Current Pricing', vi: 'Giá Hiện Tại' },
  'update_station_price': { en: 'Update Station Price', vi: 'Cập Nhật Giá Trạm' },
  'select_station': { en: 'Select station...', vi: 'Chọn trạm sạc...' },
  'new_price_kwh': { en: 'New price (VND/kWh)', vi: 'Giá mới (VNĐ/kWh)' },
  'update_price': { en: 'Update Price', vi: 'Cập Nhật Giá' },
  'peak_hours_management': { en: 'Peak Hours Management', vi: 'Quản Lý Giờ Cao Điểm' },
  'configure_peak_multipliers': { en: 'Configure peak hour pricing multipliers', vi: 'Cấu hình hệ số nhân giá giờ cao điểm' },
  'current_peak_hours': { en: 'Current Peak Hours', vi: 'Giờ Cao Điểm Hiện Tại' },
  'morning_peak': { en: 'Morning Peak', vi: 'Giờ Cao Điểm Sáng' },
  'evening_peak': { en: 'Evening Peak', vi: 'Giờ Cao Điểm Tối' },
  'weekend_peak': { en: 'Weekend Peak', vi: 'Cuối Tuần' },
  'multiplier': { en: 'multiplier', vi: 'hệ số' },
  'update_peak_multiplier': { en: 'Update Peak Hour Multiplier', vi: 'Cập Nhật Hệ Số Giờ Cao Điểm' },
  'select_peak_hour': { en: 'Select peak hour...', vi: 'Chọn giờ cao điểm...' },
  'new_multiplier': { en: 'New multiplier (e.g. 1.5)', vi: 'Hệ số mới (vd: 1.5)' },
  'update_multiplier': { en: 'Update Multiplier', vi: 'Cập Nhật Hệ Số' },
  'penalty_fees_management': { en: 'Penalty Fees Management', vi: 'Quản Lý Phí Phạt' },
  'configure_penalty_fees': { en: 'Configure penalty fees for violations', vi: 'Cấu hình phí phạt cho các vi phạm' },
  'parking_without_charging': { en: 'Parking Without Charging', vi: 'Đỗ Xe Không Sạc' },
  'fee_per_hour_parking': { en: 'Fee per hour for parking without charging', vi: 'Phí mỗi giờ đỗ xe không sạc' },
  'late_arrival_penalty': { en: 'Late Arrival Penalty', vi: 'Phí Đến Trễ' },
  'fee_per_15_minutes_late': { en: 'Fee per 15 minutes late', vi: 'Phí mỗi 15 phút trễ' },
  'hour': { en: 'hour', vi: 'giờ' },
  'min': { en: 'min', vi: 'phút' },
  'update_penalty_fees': { en: 'Update Penalty Fees', vi: 'Cập Nhật Phí Phạt' },
  'subscription_plans_management': { en: 'Subscription Plans Management', vi: 'Quản Lý Gói Đăng Ký' },
  'configure_subscription_pricing': { en: 'Configure subscription plans and pricing', vi: 'Cấu hình gói đăng ký và giá cả' },
  'current_subscription_plans': { en: 'Current Subscription Plans', vi: 'Gói Đăng Ký Hiện Tại' },
  'basic_plan': { en: 'Basic Plan', vi: 'Gói Cơ Bản' },
  'standard_plan': { en: 'Standard Plan', vi: 'Gói Tiêu Chuẩn' },
  'premium_plan': { en: 'Premium Plan', vi: 'Gói Cao Cấp' },
  'month': { en: 'month', vi: 'tháng' },
  'discount': { en: 'discount', vi: 'giảm giá' },
  'update_subscription_plan': { en: 'Update Subscription Plan', vi: 'Cập Nhật Gói Đăng Ký' },
  'select_plan': { en: 'Select plan...', vi: 'Chọn gói...' },
  'new_price_vnd': { en: 'New price (VND)', vi: 'Giá mới (VNĐ)' },
  'discount_percent': { en: 'Discount %', vi: 'Giảm giá %' },
  'update_plan': { en: 'Update Plan', vi: 'Cập Nhật Gói' },
  'back_to_dashboard': { en: 'Back to Dashboard', vi: 'Về Dashboard' },
  'current': { en: 'Current', vi: 'Hiện tại' },

  // Admin Dashboard Translations
  'admin_dashboard': { en: 'Admin Dashboard', vi: 'Bảng Điều Khiển Quản Trị' },
  'system_management_portal': { en: 'System management and monitoring portal', vi: 'Cổng quản lý và giám sát hệ thống' },
  'admin_access': { en: 'Admin', vi: 'Quản Trị' },
  'refresh': { en: 'Refresh', vi: 'Làm mới' },
  'overview': { en: 'Overview', vi: 'Tổng quan' },
  'users': { en: 'Users', vi: 'Người dùng' },
  'stations': { en: 'Stations', vi: 'Trạm sạc' },
  'system': { en: 'System', vi: 'Hệ thống' },
  'total_users': { en: 'Total Users', vi: 'Tổng Người Dùng' },
  'active': { en: 'active', vi: 'hoạt động' },
  'charging_stations': { en: 'Charging Stations', vi: 'Trạm Sạc' },
  'online': { en: 'online', vi: 'trực tuyến' },
  'total_revenue': { en: 'Total Revenue', vi: 'Tổng Doanh Thu' },
  'transactions': { en: 'transactions', vi: 'giao dịch' },
  'system_uptime': { en: 'System Uptime', vi: 'Thời Gian Hoạt Động' },
  'avg_response': { en: 'avg response', vi: 'phản hồi TB' },
  'system_health': { en: 'System Health', vi: 'Tình Trạng Hệ Thống' },
  'real_time_system_monitoring': { en: 'Real-time system performance monitoring', vi: 'Giám sát hiệu suất hệ thống thời gian thực' },
  'memory': { en: 'Memory', vi: 'Bộ nhớ' },
  'storage': { en: 'Storage', vi: 'Lưu trữ' },
  'network': { en: 'Network', vi: 'Mạng' },
  'recent_alerts': { en: 'Recent Alerts', vi: 'Cảnh Báo Gần Đây' },
  'system_alerts_and_notifications': { en: 'System alerts and important notifications', vi: 'Cảnh báo hệ thống và thông báo quan trọng' },
  'resolved': { en: 'Resolved', vi: 'Đã giải quyết' },
  'user_management': { en: 'User Management', vi: 'Quản Lý Người Dùng' },
  'manage_system_users': { en: 'Manage system users and permissions', vi: 'Quản lý người dùng hệ thống và quyền hạn' },
  'user_management_coming_soon': { en: 'User management features coming soon', vi: 'Tính năng quản lý người dùng sẽ ra mắt sớm' },
  'station_management': { en: 'Station Management', vi: 'Quản Lý Trạm Sạc' },
  'manage_charging_stations': { en: 'Manage charging stations and infrastructure', vi: 'Quản lý trạm sạc và cơ sở hạ tầng' },
  'station_management_coming_soon': { en: 'Station management features coming soon', vi: 'Tính năng quản lý trạm sạc sẽ ra mắt sớm' },
  'system_configuration': { en: 'System Configuration', vi: 'Cấu Hình Hệ Thống' },
  'advanced_system_settings': { en: 'Advanced system configuration and settings', vi: 'Cấu hình và cài đặt hệ thống nâng cao' },
  'system_config_coming_soon': { en: 'System configuration features coming soon', vi: 'Tính năng cấu hình hệ thống sẽ ra mắt sớm' },
  'admin_settings': { en: 'Admin Settings', vi: 'Cài Đặt Quản Trị' },
  'configure_admin_preferences': { en: 'Configure administrator preferences and security', vi: 'Cấu hình tùy chọn quản trị và bảo mật' },
  'admin_settings_coming_soon': { en: 'Admin settings features coming soon', vi: 'Tính năng cài đặt quản trị sẽ ra mắt sớm' },
  
  // Notification specific translations
  'back': { en: 'Back', vi: 'Quay lại' },
  'notifications': { en: 'Notifications', vi: 'Thông báo' },
  'manage_notifications_updates': { en: 'Manage your notifications and updates', vi: 'Quản lý thông báo và cập nhật của bạn' },
  'no_notifications': { en: 'No notifications', vi: 'Không có thông báo' },
  'all_notifications_appear_here': { en: 'All notifications will appear here', vi: 'Tất cả thông báo sẽ hiển thị ở đây' },
  'total_notifications': { en: 'Total notifications', vi: 'Tổng thông báo' },
  'unread': { en: 'Unread', vi: 'Chưa đọc' },
  'action_required': { en: 'Action required', vi: 'Cần hành động' },
  'mark_as_read': { en: 'Mark as read', vi: 'Đánh dấu đã đọc' },
  
  // Notification types and actions
  'invoice_badge': { en: 'Invoice', vi: 'Hóa đơn' },
  'late_arrival_badge': { en: 'Late', vi: 'Trễ giờ' },
  'charging_complete_badge': { en: 'Complete', vi: 'Hoàn thành' },
  'overstay_warning_badge': { en: 'Warning', vi: 'Cảnh báo' },
  'report_success_badge': { en: 'Report', vi: 'Báo cáo' },
  'notification_badge': { en: 'Notification', vi: 'Thông báo' },
  
  'what_would_you_like_to_do': { en: 'What would you like to do?', vi: 'Bạn muốn làm gì?' },
  'fee': { en: 'Fee', vi: 'Phí' },
  'cancel_session': { en: 'Cancel session', vi: 'Hủy lịch sạc' },
  'continue_and_pay_fee': { en: 'Continue & pay fee', vi: 'Tiếp tục & trả phí' },
  
  // Toast messages  
  'session_cancelled_successfully': { en: 'Session cancelled successfully!', vi: 'Đã hủy lịch sạc thành công!' },
  'session_cancelled_description': { en: 'Charging session {sessionId} at {location} has been cancelled', vi: 'Lịch sạc {sessionId} tại {location} đã được hủy' },
  'continue_charging_session': { en: 'Continue charging session!', vi: 'Tiếp tục phiên sạc!' },
  'late_fee_description': { en: 'Late fee {amount} VND will be added to your invoice', vi: 'Phí trễ {amount} VND sẽ được tính vào hóa đơn' },
  'notification_sent_to_staff': { en: 'Notification sent to staff', vi: 'Thông báo đã gửi cho staff' },
  'staff_notified_cancellation': { en: 'Staff will be notified about your cancellation', vi: 'Staff sẽ được thông báo về việc hủy lịch của bạn' },
  'staff_notified_late_fee': { en: 'Staff will be notified about the late fee', vi: 'Staff sẽ được thông báo về phí trễ giờ' },
  
  // Notification content templates (will be used as templates)
  'late_arrival_title': { en: '⏰ You are late for your charging appointment', vi: '⏰ Bạn đã trễ giờ đặt lịch sạc' },
  'late_arrival_message': { en: 'You are {minutes} minutes late for your charging session at {location}. Would you like to cancel or continue? Continuing will incur a {amount} VND fee.', vi: 'Bạn đã trễ quá {minutes} phút giờ đặt sạc tại {location}. Bạn có muốn hủy lịch hay tiếp tục? Nếu tiếp tục sẽ tính thêm phí {amount} VND.' },
  'overstay_warning_title': { en: '🚗 Vehicle overstay warning', vi: '🚗 Cảnh báo để xe quá lâu' },
  'overstay_warning_message': { en: 'Your vehicle has been parked at {location} without charging for over {minutes} minutes. You will be charged a {amount} VND penalty if you do not move your vehicle.', vi: 'Xe của bạn đang để tại điểm sạc {location} nhưng không sạc, đã vượt quá {minutes} phút quy định. Bạn sẽ bị tính phí phạt {amount} VND nếu không di chuyển xe.' },
  'charging_complete_title': { en: '⚡ Your vehicle has finished charging', vi: '⚡ Xe bạn đã sạc xong' },
  'charging_complete_message': { en: 'Charging process for your {vehicle} at {location} is complete. Battery is now at {percentage}%. Please move your vehicle to avoid penalties.', vi: 'Quá trình sạc pin cho xe {vehicle} tại {location} đã hoàn tất. Pin đã đạt {percentage}%. Vui lòng di chuyển xe để tránh phí phạt.' },
  'invoice_sent_title': { en: '💳 Invoice has been sent', vi: '💳 Hóa đơn đã được gửi' },
  'invoice_sent_message': { en: 'Invoice for charging session on {date} has been sent to {email}. Total amount: {amount} VND.', vi: 'Hóa đơn thanh toán cho phiên sạc ngày {date} đã được gửi về email {email}. Tổng tiền: {amount} VND.' },
  'report_success_title': { en: '📋 Report submitted successfully', vi: '�� Báo cáo đã gửi thành công' },
  'report_success_message': { en: 'Your report \'{title}\' at {location} has been successfully submitted to our technical team. We will resolve it within 24 hours.', vi: 'Báo cáo sự cố \'{title}\' tại {location} đã được gửi thành công cho đội ngũ kỹ thuật. Chúng tôi sẽ xử lý trong vòng 24h.' },
  
  // Staff Dashboard Statistics
  'support_tickets': { en: 'Support Tickets', vi: 'Ticket Hỗ Trợ' },
  'pending_invoices': { en: 'Pending Invoices', vi: 'Hóa Đơn Chờ' },
  'open_reports': { en: 'Open Reports', vi: 'Báo Cáo Mở' },
  'notifications': { en: 'Notifications', vi: 'Thông Báo' },
  
  // Subscription related translations
  'my_subscriptions': { en: 'My Subscriptions', vi: 'Gói Đăng Ký Của Tôi' },
  'subscription_plans': { en: 'Subscription Plans', vi: 'Gói Đăng Ký' },
  'manage_current_subscriptions': { en: 'Manage your current subscriptions and billing', vi: 'Quản lý các gói đăng ký và thanh toán hiện tại' },
  'choose_plan_description': { en: 'Choose the perfect plan for your charging needs', vi: 'Chọn gói phù hợp với nhu cầu sạc của bạn' },
  'active_plan': { en: 'Active Plan', vi: 'Gói Đang Hoạt Động' },
  'basic_plan': { en: 'Basic Plan', vi: 'Gói Cơ Bản' },
  'premium_plan': { en: 'Premium Plan', vi: 'Gói Cao Cấp' },
  'pro_plan': { en: 'Pro Plan', vi: 'Gói Chuyên Nghiệp' },
  'active': { en: 'Active', vi: 'Đang Hoạt Động' },
  'current_plan': { en: 'Current Plan', vi: 'Gói Hiện Tại' },
  'current': { en: 'Current', vi: 'Hiện Tại' },
  'available_plans': { en: 'Available Plans', vi: 'Các Gói Có Sẵn' },
  'popular': { en: 'Popular', vi: 'Phổ Biến' },
  'monthly': { en: 'month', vi: 'tháng' },
  'yearly': { en: 'year', vi: 'năm' },
  'upgrade_plan': { en: 'Upgrade Plan', vi: 'Nâng Cấp Gói' },
  'billing_history': { en: 'Billing History', vi: 'Lịch Sử Thanh Toán' },
  'account_management': { en: 'Account Management', vi: 'Quản Lý Tài Khoản' },
  'change_billing': { en: 'Change Billing', vi: 'Thay Đổi Thanh Toán' },
  'usage_analytics': { en: 'Usage Analytics', vi: 'Phân Tích Sử Dụng' },
  'cancel_subscription': { en: 'Cancel Subscription', vi: 'Hủy Đăng Ký' },
  
  // Additional subscription page translations
  'next_billing': { en: 'Next billing', vi: 'Thanh toán tiếp theo' },
  'amount': { en: 'Amount', vi: 'Số tiền' },
  'status': { en: 'Status', vi: 'Trạng thái' },
  'paid': { en: 'Paid', vi: 'Đã thanh toán' },
  'month': { en: 'month', vi: 'tháng' },
  
  // CustomerSupportView missing translations
  'name': { en: 'Name', vi: 'Tên' },
  'phone': { en: 'Phone', vi: 'Điện thoại' },
  'email': { en: 'Email', vi: 'Email' },
  'reported': { en: 'Reported', vi: 'Báo cáo' },
  'assigned_to': { en: 'Assigned to', vi: 'Được giao cho' },
  'urgency': { en: 'URGENCY', vi: 'KHẨN CẤP' },
  'by': { en: 'by', vi: 'bởi' },
  'issues_reported': { en: 'Issues reported', vi: 'Sự cố được báo cáo' },
  'quick_actions': { en: 'Quick Actions', vi: 'Hành Động Nhanh' },
  
  // Register page translations
  'back': { en: 'Back', vi: 'Quay lại' },
  'join_future_charging': { en: 'Join the future of EV charging', vi: 'Tham gia tương lai sạc xe điện' },
  'first_name': { en: 'First Name', vi: 'Tên' },
  'last_name': { en: 'Last Name', vi: 'Họ' },
  'enter_first_name': { en: 'Enter first name', vi: 'Nhập tên' },
  'enter_last_name': { en: 'Enter last name', vi: 'Nhập họ' },
  'create_strong_password': { en: 'Create a strong password', vi: 'Tạo mật khẩu mạnh' },
  'confirm_password': { en: 'Confirm Password', vi: 'Xác nhận mật khẩu' },
  'confirm_your_password': { en: 'Confirm your password', vi: 'Xác nhận mật khẩu của bạn' },
  'i_agree_to_the': { en: 'I agree to the', vi: 'Tôi đồng ý với' },
  'terms_of_service': { en: 'Terms of Service', vi: 'Điều khoản dịch vụ' },
  'and': { en: 'and', vi: 'và' },
  'privacy_policy': { en: 'Privacy Policy', vi: 'Chính sách bảo mật' },
  'create_chargehub_account': { en: 'Create ChargeHub Account', vi: 'Tạo tài khoản ChargeHub' },
  'or_sign_up_with': { en: 'or sign up with', vi: 'hoặc đăng ký với' },
  'already_have_account': { en: 'Already have an account?', vi: 'Đã có tài khoản?' },
  'sign_in_here': { en: 'Sign in here', vi: 'Đăng nhập tại đây' },
  'or': { en: 'or', vi: 'hoặc' },
  
  // StaffLogin translations
  'staff_portal_access': { en: 'Staff Portal Access', vi: 'Truy cập Cổng nhân viên' },
  'staff_id_email': { en: 'Staff ID / Email', vi: 'Mã nhân viên / Email' },
  'enter_staff_credentials': { en: 'Enter your staff credentials', vi: 'Nhập thông tin đăng nhập nhân viên' },
  'staff_sign_in': { en: 'Staff Sign In', vi: 'Đăng nhập nhân viên' },
  'back_to_main_login': { en: 'Back to main login', vi: 'Quay lại đăng nhập chính' },
  
  // ProfileSetup translations
  'profile_setup': { en: 'Profile Setup', vi: 'Thiết lập hồ sơ' },
  'complete_profile_to_start': { en: 'Complete your profile to get started', vi: 'Hoàn thành hồ sơ để bắt đầu' },
  'identification': { en: 'Identification', vi: 'Giấy tờ tùy thân' },
  'enter_id_number': { en: 'Enter your ID number', vi: 'Nhập số CCCD/CMND' },
  'date_of_birth': { en: 'Date of Birth', vi: 'Ngày sinh' },
  'select_date_of_birth': { en: 'Select your date of birth', vi: 'Chọn ngày sinh của bạn' },
  'phone': { en: 'Phone', vi: 'Số điện thoại' },
  'enter_phone_number': { en: 'Enter your phone number', vi: 'Nhập số điện thoại' },
  'country': { en: 'Country', vi: 'Quốc gia' },
  'select_country': { en: 'Select Country', vi: 'Chọn quốc gia' },
  'province_state': { en: 'Province/State', vi: 'Tỉnh/Thành phố' },
  'select_country_first': { en: 'Select Country First', vi: 'Chọn quốc gia trước' },
  'select_province_state': { en: 'Select Province/State', vi: 'Chọn tỉnh/thành phố' },
  'address': { en: 'Address', vi: 'Địa chỉ' },
  'street_address_placeholder': { en: 'Street Name, Alley, Add No.', vi: 'Tên đường, hẻm, số nhà' },
  'upload_image': { en: 'Upload Image', vi: 'Tải ảnh lên' },
  'change_image': { en: 'Change Image', vi: 'Đổi ảnh' },
  'select_image_from_computer': { en: 'Select Image from Computer', vi: 'Chọn ảnh từ máy tính' },
  'please_select_image_file': { en: 'Please select an image file', vi: 'Vui lòng chọn file ảnh' },
  'image_too_large': { en: 'Image file is too large. Please select a file smaller than 5MB', vi: 'File ảnh quá lớn. Vui lòng chọn file nhỏ hơn 5MB' },
  'supported_formats': { en: 'Supported: JPG, PNG, GIF', vi: 'Hỗ trợ: JPG, PNG, GIF' },
  'max_size': { en: 'Max: 5MB', vi: 'Tối đa: 5MB' },
  'error_submitting_profile': { en: 'Error submitting profile. Please try again.', vi: 'Lỗi khi gửi hồ sơ. Vui lòng thử lại.' },
  'submitting_profile': { en: 'Submitting profile...', vi: 'Đang gửi hồ sơ...' },
  'profile_submitted_successfully': { en: 'Profile submitted successfully!', vi: 'Gửi hồ sơ thành công!' },
  'please_fill_all_fields': { en: 'Please fill in all required fields', vi: 'Vui lòng điền đầy đủ các trường bắt buộc' },
  'next': { en: 'Next', vi: 'Tiếp theo' },
  
  // VehicleSetup translations  
  'vehicle_setup': { en: 'Vehicle Setup', vi: 'Thiết lập xe' },
  'register_your_vehicle': { en: 'Register your electric vehicle for charging', vi: 'Đăng ký xe điện để sạc' },
  'vehicle_brand': { en: 'Vehicle Brand', vi: 'Hãng xe' },
  'select_brand': { en: 'Select Brand', vi: 'Chọn hãng xe' },
  'vehicle_model': { en: 'Vehicle Model', vi: 'Dòng xe' },
  'select_model': { en: 'Select Model', vi: 'Chọn dòng xe' },
  'license_plate': { en: 'License Plate', vi: 'Biển số xe' },
  'enter_license_plate': { en: 'Enter your license plate number', vi: 'Nhập biển số xe' },
  'vehicle_color': { en: 'Vehicle Color', vi: 'Màu xe' },
  'select_color': { en: 'Select Color', vi: 'Chọn màu xe' },
  'complete_setup': { en: 'Complete Setup', vi: 'Hoàn tất thiết lập' },
  
  // BookingMap translations
  'back_to_dashboard': { en: 'Back to Dashboard', vi: 'Về Dashboard' },
  'book_charging_station': { en: 'Book Charging Station', vi: 'Đặt trạm sạc' },
  'find_charging_stations': { en: 'Find Charging Stations', vi: 'Tìm trạm sạc' },
  'search_stations_placeholder': { en: 'Search stations by name or location...', vi: 'Tìm trạm theo tên hoặc địa điểm...' },
  'filter_stations': { en: 'Filter stations', vi: 'Lọc trạm sạc' },
  'all_stations': { en: 'All Stations', vi: 'Tất cả trạm' },
  'available_only': { en: 'Available Only', vi: 'Chỉ trạm trống' },
  'fast_charging': { en: 'Fast Charging', vi: 'Sạc nhanh' },
  '24_7_open': { en: '24/7 Open', vi: 'Mở 24/7' },
  'showing_stations': { en: 'Showing {count} charging stations', vi: 'Hiển thị {count} trạm sạc' },
  'available': { en: 'Available', vi: 'Có sẵn' },
  'busy': { en: 'Busy', vi: 'Bận' },
  'your_location': { en: 'Your Location', vi: 'Vị trí của bạn' },
  'away': { en: 'away', vi: 'từ đây' },
  'available_ports': { en: 'Available Ports', vi: 'Cổng trống' },
  'price_per_kwh': { en: 'Price per kWh', vi: 'Giá mỗi kWh' },
  'operating_hours': { en: 'Operating Hours', vi: 'Giờ hoạt động' },
  'yes': { en: 'Yes', vi: 'Có' },
  'no': { en: 'No', vi: 'Không' },
  'charger_types': { en: 'Charger Types', vi: 'Loại sạc' },
  'amenities': { en: 'Amenities', vi: 'Tiện ích' },
  'book_this_station': { en: 'Book This Station', vi: 'Đặt trạm này' },
  'time_slot': { en: 'Time Slot', vi: 'Khung giờ' },
  'select_time': { en: 'Select time', vi: 'Chọn thời gian' },
  'now': { en: 'Now', vi: 'Bây giờ' },
  'in_1_hour': { en: 'In 1 hour', vi: 'Sau 1 giờ' },
  'in_2_hours': { en: 'In 2 hours', vi: 'Sau 2 giờ' },
  'tomorrow_9am': { en: 'Tomorrow 9:00 AM', vi: 'Ngày mai 9:00' },
  'duration': { en: 'Duration', vi: 'Thời lượng' },
  'select_duration': { en: 'Select duration', vi: 'Chọn thời lượng' },
  '30_minutes': { en: '30 minutes', vi: '30 phút' },
  '1_hour': { en: '1 hour', vi: '1 giờ' },
  '2_hours': { en: '2 hours', vi: '2 giờ' },
  '4_hours': { en: '4 hours', vi: '4 giờ' },
  'book_station': { en: 'Book Station', vi: 'Đặt trạm' },
  'confirm_booking': { en: 'Confirm Booking', vi: 'Xác nhận đặt chỗ' },
  'review_booking_details': { en: 'Please review your booking details', vi: 'Vui lòng xem xét chi tiết đặt chỗ' },
  'subscription': { en: 'Subscription', vi: 'Gói đăng ký' },
  'discount_on_charging': { en: 'discount on charging', vi: 'giảm giá cho phiên sạc' },
  'time': { en: 'Time', vi: 'Thời gian' },
  'original_price': { en: 'Original Price', vi: 'Giá gốc' },
  'discount': { en: 'Discount', vi: 'Giảm giá' },
  'total_cost': { en: 'Total Cost', vi: 'Tổng chi phí' },
  'you_save': { en: 'You save', vi: 'Bạn tiết kiệm được' },
  'confirm_book': { en: 'Confirm & Book', vi: 'Xác nhận & Đặt' },
  'booking_confirmed': { en: 'Booking Confirmed!', vi: 'Đã xác nhận đặt chỗ!' },
  'booking_success_message': { en: 'Your charging station has been successfully booked. You will receive a confirmation notification shortly.', vi: 'Trạm sạc đã được đặt thành công. Bạn sẽ nhận được thông báo xác nhận sớm.' },
  'view_booking_details': { en: 'View Booking Details', vi: 'Xem chi tiết đặt chỗ' },
  
  // StaffReportView translations
  'report_management': { en: 'Report Management', vi: 'Quản Lý Báo Cáo' },
  'submit_track_reports': { en: 'Submit and track maintenance reports', vi: 'Gửi và theo dõi báo cáo bảo trì' },
  'equipment_reports': { en: 'Equipment Reports', vi: 'Báo Cáo Thiết Bị' },
  'other_issues': { en: 'Other Issues', vi: 'Vấn Đề Khác' },
  'report_history': { en: 'Report History', vi: 'Lịch Sử Báo Cáo' },
  'customer_equipment_reports': { en: 'Customer Equipment Reports', vi: 'Báo Cáo Thiết Bị Từ Khách Hàng' },
  'review_customer_issues': { en: 'Review customer-reported equipment issues', vi: 'Xem xét sự cố thiết bị do khách hàng báo cáo' },
  'customer_report': { en: 'Customer Report', vi: 'Báo Cáo Khách Hàng' },
  'station': { en: 'Station', vi: 'Trạm' },
  'equipment': { en: 'Equipment', vi: 'Thiết Bị' },
  'issue': { en: 'Issue', vi: 'Sự Cố' },
  'date': { en: 'Date', vi: 'Ngày' },
  'create_report': { en: 'Create Report', vi: 'Tạo Báo Cáo' },
  'new_equipment_report': { en: 'New Equipment Report', vi: 'Báo Cáo Thiết Bị Mới' },
  'submit_equipment_report': { en: 'Submit equipment damage or malfunction report', vi: 'Gửi báo cáo hỏng hóc hoặc trục trặc thiết bị' },
  'report_source': { en: 'Report Source', vi: 'Nguồn Báo Cáo' },
  'select_report_source': { en: 'Select report source', vi: 'Chọn nguồn báo cáo' },
  'staff_inspection': { en: 'Staff Inspection', vi: 'Kiểm Tra Nhân Viên' },
  'customer_report_followup': { en: 'Customer Report Follow-up', vi: 'Theo Dõi Báo Cáo Khách Hàng' },
  'select_station': { en: 'Select station', vi: 'Chọn trạm' },
  'equipment_type': { en: 'Equipment Type', vi: 'Loại Thiết Bị' },
  'select_equipment': { en: 'Select equipment', vi: 'Chọn thiết bị' },
  'report_title': { en: 'Report Title', vi: 'Tiêu Đề Báo Cáo' },
  'brief_description_issue': { en: 'Brief description of the issue', vi: 'Mô tả ngắn gọn về sự cố' },
  'priority_level': { en: 'Priority Level', vi: 'Mức Độ Ưu Tiên' },
  'low': { en: 'Low', vi: 'Thấp' },
  'medium': { en: 'Medium', vi: 'Trung Bình' },
  'high': { en: 'High', vi: 'Cao' },
  'critical': { en: 'Critical', vi: 'Nghiêm Trọng' },
  'detailed_description': { en: 'Detailed Description', vi: 'Mô Tả Chi Tiết' },
  'equipment_issue_placeholder': { en: 'Provide detailed information about the equipment issue, symptoms, and any troubleshooting steps taken...', vi: 'Cung cấp thông tin chi tiết về sự cố thiết bị, triệu chứng và các bước khắc phục đã thực hiện...' },
  'photos_optional': { en: 'Photos (Optional)', vi: 'Ảnh (Tùy chọn)' },
  'upload_photos_issue': { en: 'Upload photos of the equipment issue', vi: 'Tải lên ảnh sự cố thiết bị' },
  'choose_photos': { en: 'Choose Photos', vi: 'Chọn Ảnh' },
  'reset_form': { en: 'Reset Form', vi: 'Đặt Lại Form' },
  'submit_report': { en: 'Submit Report', vi: 'Gửi Báo Cáo' },
  'report_other_issues': { en: 'Report Other Issues', vi: 'Báo Cáo Vấn Đề Khác' },
  'submit_non_equipment_reports': { en: 'Submit reports for non-equipment related problems', vi: 'Gửi báo cáo cho các vấn đề không liên quan đến thiết bị' },
  'station_optional': { en: 'Station (Optional)', vi: 'Trạm (Tùy chọn)' },
  'select_station_if_applicable': { en: 'Select station if applicable', vi: 'Chọn trạm nếu có' },
  'no_specific_station': { en: 'No specific station', vi: 'Không có trạm cụ thể' },
  'issue_title': { en: 'Issue Title', vi: 'Tiêu Đề Sự Cố' },
  'issue_description': { en: 'Issue Description', vi: 'Mô Tả Sự Cố' },
  'other_issue_placeholder': { en: 'Describe the issue in detail (e.g., lighting problems, cleanliness issues, safety concerns, parking problems, etc.)', vi: 'Mô tả chi tiết sự cố (ví dụ: vấn đề ánh sáng, vấn đề vệ sinh, mối quan tâm an toàn, vấn đề đỗ xe, v.v.)' },
  'upload_photos_support': { en: 'Upload photos to support your report', vi: 'Tải lên ảnh để hỗ trợ báo cáo' },
  'view_track_reports': { en: 'View and track submitted reports', vi: 'Xem và theo dõi các báo cáo đã gửi' },
  'type': { en: 'Type', vi: 'Loại' },
  'related_customer_report': { en: 'Related to customer report', vi: 'Liên quan đến báo cáo khách hàng' },
  'view_details': { en: 'View Details', vi: 'Xem Chi Tiết' },
  
  // StaffDashboard notifications section
  'notifications_management': { en: 'System notifications and alerts management', vi: 'Quản lý thông báo và cảnh báo hệ thống' },
  'unread': { en: 'Unread', vi: 'Chưa đọc' },
  'today': { en: 'Today', vi: 'Hôm nay' },
  'critical': { en: 'Critical', vi: 'Nghiêm trọng' },
  'view_all_notifications_detailed': { en: 'View all detailed notifications', vi: 'Xem tất cả thông báo chi tiết' },
  'recent_notifications_preview': { en: 'Recent Notifications (Preview)', vi: 'Thông Báo Gần Đây (Xem Trước)' },
  'view_all_notifications': { en: 'View All', vi: 'Xem Tất Cả' },
  
  // Sample notification content
  'user_decision_required': { en: 'User Decision Required', vi: 'Cần Quyết Định Người Dùng' },
  'customer_continue_after_late': { en: 'Customer decided to continue charging session after late arrival', vi: 'Khách hàng quyết định tiếp tục phiên sạc sau khi đến muộn' },
  'overstay_alert': { en: 'Overstay Alert', vi: 'Cảnh Báo Ở Lại Quá Lâu' },
  'vehicle_parked_without_charging': { en: 'Vehicle parked at station for 15+ minutes without charging', vi: 'Xe đậu tại trạm hơn 15 phút mà không sạc' },
  'new_report_received': { en: 'New Report Received', vi: 'Nhận Báo Cáo Mới' },
  'customer_reported_malfunction': { en: 'Customer reported charging station malfunction', vi: 'Khách hàng báo cáo trạm sạc bị trục trặc' },
  '5_minutes_ago': { en: '5 minutes ago', vi: '5 phút trước' },
  '15_minutes_ago': { en: '15 minutes ago', vi: '15 phút trước' },
  '1_hour_ago': { en: '1 hour ago', vi: '1 giờ trước' },
  
  // Pay Later feature
  'pay_later': { en: 'Pay Later', vi: 'Trả Sau' },
  'pay_later_wallet': { en: 'Pay Later Wallet', vi: 'Ví Trả Sau' },
  'credit_limit': { en: 'Credit Limit', vi: 'Hạn Mức Tín Dụng' },
  'current_debt': { en: 'Current Debt', vi: 'Nợ Hiện Tại' },
  'available_credit': { en: 'Available Credit', vi: 'Tín Dụng Có Sẵn' },
  'due_date': { en: 'Due Date', vi: 'Ngày Đáo Hạn' },
  'minimum_payment': { en: 'Minimum Payment', vi: 'Số Tiền Tối Thiểu' },
  'pay_later_history': { en: 'Pay Later History', vi: 'Lịch Sử Trả Sau' },
  'pay_debt': { en: 'Pay Debt', vi: 'Trả Nợ' },
  'pay_later_description': { en: 'Use credit for charging when your wallet balance is low', vi: 'Sử dụng tín dụng để sạc khi số dư ví thấp' },
  'pending_payment': { en: 'Pending Payment', vi: 'Chờ Thanh Toán' },
  'pay_later_charge': { en: 'Pay Later Charge', vi: 'Sạc Trả Sau' },
  'pay_later_payment': { en: 'Pay Later Payment', vi: 'Thanh Toán Trả Sau' },
  'debt_settlement': { en: 'Debt Settlement', vi: 'Thanh Toán Nợ' },
  'emergency_charging': { en: 'Emergency Charging', vi: 'Sạc Khẩn Cấp' },
  'fast_charging': { en: 'Fast Charging', vi: 'Sạc Nhanh' },
  'payment_amount': { en: 'Payment Amount', vi: 'Số Tiền Thanh Toán' },
  'select_payment_card': { en: 'Select Payment Card', vi: 'Chọn Thẻ Thanh Toán' },
  'pay_now': { en: 'Pay Now', vi: 'Thanh Toán Ngay' },
  'full_payment': { en: 'Full Payment', vi: 'Thanh Toán Đầy Đủ' },
  'partial_payment': { en: 'Partial Payment', vi: 'Thanh Toán Một Phần' },
  
  // Exit confirmation popup
  'exit_confirmation_title': { en: 'Exit Role Selection?', vi: 'Thoát khỏi chọn vai trò?' },
  'exit_confirmation_message': { en: 'If you exit now, you will need to re-enter all your information when you log in again. Are you sure you want to leave?', vi: 'Nếu bạn thoát bây giờ, bạn sẽ cần nhập lại tất cả thông tin khi đăng nhập lại. Bạn có chắc chắn muốn thoát?' },
  'stay_and_continue': { en: 'Stay and Continue', vi: 'Ở lại và tiếp tục' },
  'exit_anyway': { en: 'Exit Anyway', vi: 'Thoát dù sao' }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize with localStorage value to avoid unnecessary setState
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      return savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi') ? savedLanguage : 'en';
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}